version: '2'
services:
  learninglocker:
    build: .
    image: learninglocker:latest
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  redis:
    image: redis
    ports:
      - "5379:6379"

  nginx:
    image: nginx
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
    ports:
      - "90:80"
      - "9090:8080"
      - "9091:8081"
    depends_on:
      - learninglocker
